### ISSUE TITLE
The 'pairwise2.align.globalms' function is sometimes not returning any alignments

### ISSUE THREAD

**Issue by dhauge** [biopython/biopython#1532]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
CPython
Darwin-17.4.0-x86_64-i386-64bit
1.70
```

Calls to `Bio.pairwise2.align.globalms` with some sequences and weights return no alignments. Unless I am missing some subtlety of the algorithm it should always return something because there are always alignments, so there must be at least one best one.

One problematic set of arguments is demonstrated by
```python
import Bio.pairwise2
print(Bio.pairwise2.align.globalms('GGCGCTGGGACGCCTGCTCACTGGGCGCT', 'GGAGCAGGGAGCCAGTCACCCTGGGAGCCTGGACCA', 1.0, -0.5, -1.75, -0.25, penalize_end_gaps=(True, False)))
```

This is new in `1.68`; version `1.67` did return results.

### Expected behaviour

In v1.67, this prints
```python
[('GGCGCTGGGACGCCTGCTCAC--TGGGCGC-T------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCA--CTGGGCGC-T------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTG-CTCACTGGGCGC-T------', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37), ('GGCGCTGGGACGCCTGCTCAC--TGGGCG-CT------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCA--CTGGGCG-CT------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTG-CTCACTGGGCG-CT------', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37), ('GGCGCTGGGACGCCTGCTCAC--TGGGCGCT-------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCA--CTGGGCGCT-------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTG-CTCACTGGGCGCT-------', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37), ('GGCGCTGGGACGCCTGCTCAC--TGGGCGC-------T', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCA--CTGGGCGC-------T', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTG-CTCACTGGGCGC-------T', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37), ('GGCGCTGGGACGCCTGCTCAC--TGGGCG-------CT', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCA--CTGGGCG-------CT', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTG-CTCACTGGGCG-------CT', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37)]
```

### Actual behaviour

In v1.70, this prints
```python
[]
```

The problem may be with the `penalize_end_gaps=(True, False)` option, because without that it does return a nonempty list of results:
```python
>>> print(Bio.pairwise2.align.globalms('GGCGCTGGGACGCCTGCTCACTGGGCGCT', 'GGAGCAGGGAGCCAGTCACCCTGGGAGCCTGGACCA', 1.0, -0.5, -1.75, -0.25))
[('GGCGCTGGGACGCCTG-CTCACTGGGCG-------CT', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37), ('GGCGCTGGGACGCCTGCTCA--CTGGGCG-------CT', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCAC--TGGGCG-------CT', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTG-CTCACTGGGCGC-------T', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37), ('GGCGCTGGGACGCCTGCTCA--CTGGGCGC-------T', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCAC--TGGGCGC-------T', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTG-CTCACTGGGCGCT-------', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37), ('GGCGCTGGGACGCCTGCTCA--CTGGGCGCT-------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCAC--TGGGCGCT-------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTG-CTCACTGGGCGC-T------', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37), ('GGCGCTGGGACGCCTGCTCA--CTGGGCGC-T------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCAC--TGGGCGC-T------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTG-CTCACTGGGCG-CT------', 'GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA', 10.75, 0, 37), ('GGCGCTGGGACGCCTGCTCA--CTGGGCG-CT------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38), ('GGCGCTGGGACGCCTGCTCAC--TGGGCG-CT------', 'GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA', 10.75, 0, 38)]
```

**Comment by MarkusPiotrowski** [comment]
Thank you for reporting, I will have a look into it. May take some days, though.

**Comment by MarkusPiotrowski** [comment]
@dhauge Good news for me, the v1.67 result was wrong. Actually there is a better alignment with score 11.

Good news for you: There may be a workaround by reversing the sequence input and reversing the ```penalize_end_gaps``` parameters. 

```python
>>> from Bio import pairwise2 as pw2
>>> print(pw2.align.globalms('GGAGCAGGGAGCCAGTCACCCTGGGAGCCTGGACCA', 'GGCGCTGGGACGCCTGCTCACTGGGCGCT',  1.0, -0.5, -1.75, -0.25, penalize_end_gaps=(False, True)))
[('GGAGCAGGGA-GCCAGTCACCCTGGGAGCCTGGACCA-', 'GGCGCTGGGACGCCTG-CTCACTGGGCGC--------T', 11.0, 0, 38), ('GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA-', 'GGCGCTGGGACGCCTGCTCA--CTGGGCGC--------T', 11.0, 0, 39), ('GGAGCAGGGA-GCCAG-TCACCCTGGGAGCCTGGACCA-', 'GGCGCTGGGACGCCTGCTCAC--TGGGCGC--------T', 11.0, 0, 39)]
```
So, if you receive an empty alignment, you can try to reverse sequence input and change ```penalize_end_gaps``` accordingly. Please let me known when you encounter cases where you receive empty alignments in both cases.

Of course, this is not the solution to the problem. I'm still investigating, as far as I can tell the score matrices and backtrace matrices have the same content in both cases (just reversed), so the problem is most likely in the backtrace method (```recover_alignments```).

**Comment by dhauge** [comment]
Thanks! I'll try the workaround

Here is a smaller case I encountered
```python
import Bio.pairwise2
print(Bio.pairwise2.align.globalms("AT", "AGCAGCTGGCTACCAAGGCTGCTCGCAAG", 1.0, -0.5, -1.75, -0.25, penalize_end_gaps=(True, False)))
```
For `1.70` it returns
```python
[]
```
whereas for `1.67` it returns
```python
[('A---------------------T------', 'AGCAGCTGGCTACCAAGGCTGCTCGCAAG', -7.75, 0, 29), ('A------------------T---------', 'AGCAGCTGGCTACCAAGGCTGCTCGCAAG', -7.75, 0, 29), ('A---------T------------------', 'AGCAGCTGGCTACCAAGGCTGCTCGCAAG', -7.75, 0, 29), ('A-----T----------------------', 'AGCAGCTGGCTACCAAGGCTGCTCGCAAG', -7.75, 0, 29), ('AT---------------------------', 'AGCAGCTGGCTACCAAGGCTGCTCGCAAG', -7.75, 0, 29), ('A---------------------------T', 'AGCAGCTGGCTACCAAGGCTGCTCGCAAG', -7.75, 0, 29), ('---------------------------AT', 'AGCAGCTGGCTACCAAGGCTGCTCGCAAG', -7.75, 0, 29)]
```

And removing 1 base pair from the end makes it start returning results. On `1.70`
```python
>>> print(Bio.pairwise2.align.globalms("AT", "AGCAGCTGGCTACCAAGGCTGCTCGCAA", 1.0, -0.5, -1.75, -0.25, penalize_end_gaps=(True, False)))
[('---------------------------AT', 'AGCAGCTGGCTACCAAGGCTGCTCGCAA-', -7.25, 0, 29)]
```

**Comment by dhauge** [comment]
Stepping through the code in `_recover_alignments`, the short example above seems to hit the `dead_end = True` in
```python
            elif trace in (8, 24):  # = row extend = extend gap in seqA
                trace -= 8
                if col_gap:
                    dead_end = True
                else:
                    col_gap = False
                    # We need to find the starting point of the extended gap
                    x = _find_gap_open(sequenceA, sequenceB, ali_seqA,
                                       ali_seqB, end, row, col, col_gap,
                                       gap_char, score_matrix, trace_matrix,
                                       in_process, gap_A_fn, col, row, 'col')
                    ali_seqA, ali_seqB, row, col, in_process, dead_end = x
```
Is that really the correct behavior? Looking at the reverse of the alignments of the reversed strings gives an alignment with score `-7.5`
```python
A----------------------------T
AGCAGCTGGCTACCAAGGCTGCTCGCAAG-
```
Which is a case where, iterating from the end, a `col_gap`  gets ended by opening a `row_gap`, so it seems it shouldn't be discarded by `dead_end = True`.

**Comment by dhauge** [comment]
Here's an even more minimal example
```python
>>> print(Bio.pairwise2.align.globalms("AT", "AGG", 1.0, -0.5, -1.75, -0.25, penalize_end_gaps=(True, False)))
[]
```

**Comment by MarkusPiotrowski** [comment]
@dhauge Yes, I spotted the problem at the same position. With ```Biopython 1.68``` on it is possible to have aligments where a gap in one sequence is followed by a gap in another sequences. This is the correct implementation of Gotoh's original algorithm. So the following alignment is valid and, depending on the costs you assign, also has a higher score:
```
A-
-B
```
This was not possible with the older implementation. However, we don't want to have a bunch of redundant alignments with the same meaning like this:
```
A-       -A
-B       B-
```
So I just don't allow the second case, and this is where ```dead_end``` comes into play. The rationale was that the second case has the same score like the first case, so there is no problem in forbidding the second case since we still have the first case. This is, however, __only true if the costs are the same for both strands__. I haven't foreseen cases where the costs are different for both strands, and this is exactly what happens here. The end-gap does cost nothing in the one sequence, but the gap in the other sequence would cost something. So we only get the alignment of the second type, but this is forbidden. If we reverse the sequence input the alignment is of the first type and this is fine.
No I have to find a sensible way to allow the second case also. One way would be to just allow them, however this would result in double amounts of returned alignments or, since the maximum number of alignments is 1000, we would loose other, non-redundant alignments.

**Comment by peterjc** [comment]
Nicely explained Markus. That sounds tricky.

**Comment by dhauge** [comment]
There are similar problems with redundant alignments in cases like
```python
AGGT    AGGT
A-GT    AG-T
```
that we encounter a lot but which would not be covered by logic specific to gaps. We have problems when these happen at several distinct locations in the alignment, so the number of distinct but equally scored alignments explodes exponentially.

Does the case you describe occur significantly more often in practice than more general cases of alternate but similar paths with the same score like the one above? E.g. is it worth spending time trying to find a solution for one but not the other? This is currently a bit of a half-baked thought, but could on try to note when one reaches the same position in the traceback matrix by alternate routes, and work back to the last branch point to see if the current alignment should be considered redundant with the previous one? Perhaps one could note in each entry the `in_process` stack the positions in the alignment so far where there was a branch point in the trace.

**Comment by peterjc** [comment]
Pull request #1563 by @MarkusPiotrowski  (which has just been merged) should fix this.

@dhauge Are you able to install the latest Biopython default master branch from GitHub to test this?

**Comment by dhauge** [comment]
Yes, I can test the latest version in the master branch.

**Comment by MarkusPiotrowski** [comment]
This has been fixed with PR #1563.

Closing this now.

**Comment by michaelsilverstein** [comment]
I'm using version 1.76 and I am still experiencing this problem when aligning with `penalize_end_gaps=False`. I've tried manually swapping sequence as A and B and that hasn't worked. The only way I've managed to get a result is by setting `penalize_end_gaps=True`.

**Comment by MarkusPiotrowski** [comment]
Good to hear that you find a solution. Still, can you share an example where you didn't get an alignment?

**Comment by michaelsilverstein** [comment]
Hm, I'm having trouble replicating the behavior - may have been caused by a bug in my code that I have since fixed. If it comes up again I'll post again.
