### ISSUE TITLE
BioPython Entrez.efetch module has an issue when parsing text with html tags (when rettype='xml')

### ISSUE THREAD

**Issue by sweng66** [biopython/biopython#1665]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:
```
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-17.2.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.68
>>> 
```

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in *)

**Comment by mdehoon** [comment]
I believe this has been fixed by pull request #1640 .
Can you try again with that version?

**Comment by sweng66** [comment]
OK. Thanks! I will take a look.



________________________________

**Comment by sweng66** [comment]
I upgraded BioPython from 1.68 to 1.71, but the issue is still there. Am I missing anything?


By the way, we are still using python 2.7.10. Anything related to the Python version or should I upgrade to a different version of BioPython?


Thank you!

________________________________

**Comment by sweng66** [comment]
Pull request #1640<https://github.com/biopython/biopython/pull/1640> was only merged recently - it was not in Biopython 1.71, but should be part of the next release Biopython 1.72.

  *   I see. When will 1.72 be released?

Are you comfortable with installing and testing Biopython from GitHub?

  *   No, I am not. Any link that I can follow?

Thanks!




________________________________

**Comment by peterjc** [comment]
I would hope we'd do the Biopython 1.72 release next month, before the GCCBOSC2018 meeting where I'll be giving the *Biopython Project Update 2018* talk: https://gccbosc2018.sched.com/

If you want to try this first, you need to download Biopython from GitHub (either ``git clone https://github.com/biopython/biopython.git`` at the command line, or just as a snapshot using https://github.com/biopython/biopython/archive/master.zip or https://github.com/biopython/biopython/archive/master.tar.gz instead) and install from source.

On the Apple macOS you need to install the compiler tools, see https://biopython.org/wiki/Download and/or https://github.com/biopython/biopython/blob/master/README.rst

**Comment by sweng66** [comment]
OK. Thanks for the update. =)



________________________________

**Comment by peterjc** [comment]
I'm going to close this as a duplicate of #1539, fixed by #1640.

Thank you for reporting this.
