### ISSUE TITLE
entrez.read NotImplementedError

### ISSUE THREAD

**Issue by nstfk** [biopython/biopython#1801]
I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
CPython
Windows-10-10.0.17134-SP0
1.72
```

### Expected behaviour

fetching the articles

### Actual behaviour

`NotImplementedError:` The Bio.Entrez parser cannot handle XML data that make use of XML namespaces

### Steps to reproduce
    targetQ="personalized medicine"
    handle = Entrez.esearch(db="pubmed", term=targetQ, RetMax=5000)
    Rlist = Entrez.read(handle)
    IDlist = Rlist["IdList"]
    fetch_handle = Entrez.efetch(db="pubmed", id=IDlist, rettype="null", retmode="xml", parsed=True)

**Comment by peterjc** [comment]
Most of the NCBI XML files use a DTD which is required for the ``Bio.Entrez`` parser. For the problem databases you might try ``ElementTree`` from the standard library. i.e. This is the expected behaviour for some NCBI databases' XML output, but that could be made more explicit in the message and also the documentation including the Tutorial: https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_entrez.tex

I would investigate further but right now the NCBI is giving me ``HTTP Error 403: Forbidden`` for the
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi call at the command line...

```
>>> try:
...     fetch_handle = Entrez.efetch(db="pubmed", id=IDlist, rettype="null", retmode="xml", parsed=True)
... except Exception as e:
...     print(e, e.url)
... 
HTTP Error 403: Forbidden http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi
```

This may be a temporary problem at the NCBI side, there are pubmed changes happening:

https://www.ncbi.nlm.nih.gov/mailman/pipermail/utilities-announce/2018-August/000133.html
https://www.ncbi.nlm.nih.gov/mailman/pipermail/utilities-announce/2018-September/000136.html

**Comment by mdehoon** [comment]
The new DTD now include MathML, which does indeed make use of XML namespaces. The XML parser in Bio.Entrez does not yet handle XML namespaces.

**Comment by peterjc** [comment]
Shall we retitle this to something like "Entrez parser support for MathML in PubMed XML with new DTD"?

**Comment by mdehoon** [comment]
This is an example of a pubmed record that uses MathML:
```python
Entrez.efetch(db="pubmed", id='30230595', rettype="null", retmode="xml", parsed=True)
```
This is the XML fragment where MathML is being used:
```
                <AbstractText Label="METHODS" NlmCategory="METHODS">A fat-water signal model with multiple fat peaks was used to simultaneously estimate the temperature, fat/water intensity and <mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML">
                        <mml:mrow>
                            <mml:msubsup>
                                <mml:mi>T</mml:mi>
                                <mml:mn>2</mml:mn>
                                <mml:mo>*</mml:mo>
                            </mml:msubsup>
                        </mml:mrow>
                    </mml:math> , and field offset. In DITE, model fitting was implemented with alternating 2-step minimizations. The estimated temperature map was smoothed between the 2-step minimizations, which is considered to be the most important step for improving the temperature precision. The performance of DITE was evaluated with a Monte Carlo simulation, fat/water phantoms, and ex vivo brown adipose tissue experiments and then compared with the performance of previous fat-referenced proton resonance frequency shift methods.</AbstractText>
```
The MathML is rendered as a T followed by a subscript 2 and a superscript *.
Any opinions on how we want to represent this in Python?

**Comment by peterjc** [comment]
This specific example only using subscripts and subscripts could have been described with simple HTML tags, but I assume there are more complex examples in other abstracts.

I presume that for backward compatibility we want to continue to present the abstract as a single string (or string subclass), in which perhaps we are best off  leaving the XML alone? However, for that to be useful, the whole abstract needs to be valid HTML/XML fragment, so we need to ensure things like ``<``, ``>`` and ``&`` are appropriately HTML encoded. How best to handle those is open issue #1742.

See also similar issues for HTML fragments in the abstract, e.g. #1539. Can we now get MathML in the title too?

**Comment by peterjc** [comment]
@mdehoon Is this (MathML) now also fixed by #1811?

**Comment by mdehoon** [comment]
Fixed by pull request #1823

**Comment by alcantarar** [comment]
The error is still occurring in some cases: 

### Expected Behaviour
retrieving paper by ID  
### Actual Behaviour
`NotImplementedError:` The Bio.Entrez parser cannot handle XML data that make use of XML namespaces
### Steps to reproduce  
````
idnum='31013170'
Entrez.email = 'your.email@example.com'
handle = Entrez.efetch(db='pubmed',retmode='xml',id=idnum)
paper = Entrez.read(handle)
print(paper['PubmedArticle'][0]['MedlineCitation']['Article']['ArticleTitle'])
````
This is the paper's page on pubmed: [https://www.ncbi.nlm.nih.gov/pubmed/31013170](https://www.ncbi.nlm.nih.gov/pubmed/31013170)

**Comment by mdehoon** [comment]
Works for me, using the current source code of Biopython in github.

**Comment by alcantarar** [comment]
Aaand I was running an outdated version of biopython. `biopython-1.73` works. Thanks.
