### ISSUE TITLE
Bio.Align.PairwiseAligner memory leak

### ISSUE THREAD

**Issue by jil24** [biopython/biopython#2758]
### Setup

I am reporting a problem with Biopython version 1.76, CPython version 2.7.16, and operating
system Mac OS 10.14:

repeatedly finding local alignments using Bio.Align.PairwiseAligner continually increases python memory usage. Unclear to me if this is a python problem or a problem in the C extension module. In this example no alignment results are retrieved or saved, but memory usage still accumulates.

### Reproducible example

```python
from Bio import Align
from random import randrange

letters = 'ACGT'
probelength = 20
targetlength = 5000

target = "".join([letters[randrange(0,3)] for x in range(targetlength)])
offset = randrange(0,targetlength-probelength-1)
probe = target[offset:offset+probelength]

def align(probe, target):
    aligner = Align.PairwiseAligner()
    aligner.mode = 'local'
    aligner.match_score = 1
    aligner.mismatch_score = -1
    aligner.open_gap_score = -1
    aligner.extend_gap_score = -1
    alignments = aligner.align(probe, target)

for iteration in range(10000):
    align(probe, target)
    print("iteration {}".format(iteration))
```

**Comment by mdehoon** [comment]
Fixed by #2760 .

**Comment by orangeSi** [comment]
After I update biopython to lastest 1.79, this bug still exists.

**Comment by orangeSi** [comment]
> ```python
> from Bio import Align
> from random import randrange
> 
> letters = 'ACGT'
> probelength = 20
> targetlength = 5000
> 
> target = "".join([letters[randrange(0,3)] for x in range(targetlength)])
> offset = randrange(0,targetlength-probelength-1)
> probe = target[offset:offset+probelength]
> 
> def align(probe, target):
>     aligner = Align.PairwiseAligner()
>     aligner.mode = 'local'
>     aligner.match_score = 1
>     aligner.mismatch_score = -1
>     aligner.open_gap_score = -1
>     aligner.extend_gap_score = -1
>     alignments = aligner.align(probe, target)
> 
> for iteration in range(10000):
>     align(probe, target)
>     print("iteration {}".format(iteration))
> ```



In the local mode , this bug disapper, but in the global mode```aligner.mode='global'```, the bug still exists.
```
from Bio import Align
from random import randrange

letters = 'ACGT'
probelength = 20
targetlength = 5000

target = "".join([letters[randrange(0,3)] for x in range(targetlength)])
offset = randrange(0,targetlength-probelength-1)
probe = target[offset:offset+probelength]

def align(probe, target):
    aligner = Align.PairwiseAligner()
    aligner.mode = 'global'
    aligner.match_score = 1
    aligner.mismatch_score = -1
    aligner.open_gap_score = -1
    aligner.extend_gap_score = -1
    alignments = aligner.align(probe, target)

for iteration in range(10000):
    align(probe, target)
    print("iteration {}".format(iteration))
```

**Comment by mdehoon** [comment]
@orangeSi  I can replicate this bug for local and global alignments with Biopython 1.76, but not with 1.77 or later. Are you sure you are importing Biopython 1.79 (the most recent version)?

**Comment by orangeSi** [comment]
@mdehoon  sorry, I gave the wrong parameters. but with below parameters in ``` align3```, the memory still raise large. If change to local mode in ```align3```, the memory will be ok.
```
import Bio
from Bio import Align
from random import randrange
print(Bio.__version__)

letters = 'ACGT'
probelength = 20
targetlength = 5000

target = "".join([letters[randrange(0,3)] for x in range(targetlength)])
offset = randrange(0,targetlength-probelength-1)
probe = target[offset:offset+probelength]

def align3(probe, target):
    aligner = Align.PairwiseAligner()
    aligner.mode = 'global' # with local, memory is ok; but with global, memory will raise very large.
    aligner.match_score = 2
    aligner.mismatch_score = -3
    aligner.open_gap_score = -5
    aligner.extend_gap_score = -2
    alignments = aligner.align(probe, target)

def align1(probe, target):
    aligner = Align.PairwiseAligner()
    aligner.mode = 'local' # with local and global, memory both ok!
    aligner.match_score = 1
    aligner.mismatch_score = -1
    aligner.open_gap_score = -1
    aligner.extend_gap_score = -1
    alignments = aligner.align(probe, target)

for iteration in range(1000000):
    #align1(probe, target)
    align3(probe, target)
```
above code print ```1.79 ```

**Comment by mdehoon** [comment]
Fixed by #3830.

**Comment by orangeSi** [comment]
ok, lastet master branch have fixed the bug! Thanks~
