### ISSUE TITLE
Bio.Phylo.PAML.codeml's results parser quietly fails to read all the data

### ISSUE THREAD

**Issue by a1ultima** [biopython/biopython#483]
For a prettier version of the following go here: http://stackoverflow.com/posts/20872441/edit, or here: https://www.biostars.org/p/89848/.

**Biopython** comes with methods to interface with the **PAML** package for phylogenetic analysis.

In particular I am using [**Bio.Phylo.PAML**](http://biopython.org/wiki/PAML) to run analyses using PAML's codeml.exe program which in my case does Ka/Ks (dN/dS) ratio analysis on pairs of orthologous gene sequences.

After running the analysis using `results = cml.run()` I can see it has successfully generated `result.out` files that look about right. Most importantly the final line of the file is what I need to parse into Python:

```
t= 0.2173  S=   703.9  N=  1489.1  dN/dS=  0.2247  dN = 0.0344  dS = 0.1529
```

What I am most interested in is `dN/dS = 0.2247`

According to Biopython's [**PAML wiki**](http://biopython.org/wiki/PAML) this value can be obtained from Python by doing `results = cml.run()` which generates a dictionary with a set of values I am interested in after running the analysis. The wiki claims I can find the values I need in a key called `'parameters'`. But this only returns one of the values I need `t= 0.2173`, look: 

```
>>> results.values()
['Fcodon', 'One dN/dS ratio for branches, ', '4.7b', {0: {'description': 'one-ratio', 'parameters': {'t': 0.1982}}}, {'htlv': {}, 'stlv': {}}]
```

Notice, that my parameters key only contains the `t= 0.2173` and has omitted `S=   703.9  N=  1489.1  dN/dS=  0.2247  dN = 0.0344  dS = 0.1529`

Could anybody with `codeml` experience explain to me why the parser fails to yield most of the parameters (values) I am interested in?

**Extra details**
- Using Python2.7, PAML4.7a
- Running on Windows 7
- I will readily edit in any data or info you require to help me fix this

**Comment by peterjc** [comment]
I thought this looked familiar - your BioStar question was originally over a year ago https://www.biostars.org/p/89848/

Which version of Biopython are you using here? CC @brandoninvergo

**Comment by brandoninvergo** [comment]
Could you please provide the results file?  Even better would be an alignment, tree and parameters that cause the problem.

The huge combination of possible parameters, the changing output under different parameter combos, and the occasionally changing output from one PAML version to the next all mean that it is very likely that the parser doesn't know how to handle your particular situation.

**Comment by brandoninvergo** [comment]
Also, as a sanity check, have you run the Bio.Phylo.PAML unit tests?

**Comment by a1ultima** [comment]
Hi @brandoninvergo,

Do you still want me to replicate this bug/get the results file for you? Maybe it's already fixed by now?

**Comment by brandoninvergo** [comment]
I think it's sorted now @a1ultima, thanks.

**Comment by jconover11** [comment]
I still have this bug in PAML4.9. Should I just reinstall the older version (4.7) to fix it? Or is there another way around it?

**Comment by brandoninvergo** [comment]
Very sorry for the late reply. Are you using the latest Biopython version on Git?

**Comment by jconover11** [comment]
Yes, I did find the newest updates. Thanks for the reply!

**Comment by brandoninvergo** [comment]
Sorry, do you mean you've updated and it now works, or that you've updated and you still have the problem?

**Comment by jconover11** [comment]
Whoops, I should have been more specific. I have the correct update, and I've gotten it to work now. Thanks!

**Comment by brandoninvergo** [comment]
OK, glad to hear it works now!

**Comment by lalalagartija** [comment]
Hi ! I have the same issue and the latest version of biopython and it stilll does not work. 
Here comes attachaed one of the outputs I have an issue with

`      4    573

brc                             ATG CTA CAG ATC TAC TCG ACT ATT CTT TCT CTT TAC AAG GAA CCC AAA GAC ATG TAC AAG GTA TGT TCT CTC TTC ATG AAC ATC CTC TCT AAC AAG GGT TTC TGG AAA AAG AGA CAT GAG AGA GAA GGT TTA CCT TAT CTA GAA AGC AGT CTG TCT CAT CTG AGA GCT TAC TAT TTA ACC AGA GAG TTT GTA ACC AAG AAG GCA ATT CTC TCT TGC CAT CTG TCT AAA TTG CCT TTC TTT CCT TCT TTT TCC CAA AGA CAA AAA CGG GTT CCA GAT TCC ATC GTT TTA AAT AGA AGT ATT CTC TAT TAC TAC AAA GGA TAT TCG GGT CGA GGA ATT AGA TAC GAT CGC AGT TCA TGT AAA GCT AAT ATC AAC CTC GTC TTC GCA GCC AAT TAT ACC GGC CCA GGT CCT AAT CTA GAG GTG AGA GTA AAT TTG GAA AGA ATG AGG TTT GGT AAT TAT AAT TTT TGC CTT TAC ACT TAC CTA GAA GAT GAG CAA GGA CGT AAA GTG GGG GTT GTT CTG GAG AAC ACT CTC ATT GAT ACA GAA CAG GCT CTC TCT TTC TAC CTC GAT ATG CAC AAG 
cedratDY0                       ATG CTT CAA GTC TAC TCG ACC ATT CTC TCC TTC CAC GAG GAA CCT AAG GAT GCG TAT CGG GTC TGT TCT CTC TTC ATG AAC ATC CTC TCC AGT AAA AGT TTT TGG AAA GAG AGA CAT GAG AGA GAA GGT TTA CCT TGT CTG GAA CAC AAC CTG TCT CAT ATG AGA GCC TAC TAT TTA ACC AGA GAG TTT GTA ACC AAG AAG ACA GTT CTC TCT TGT CAT CTG TCT AAA TTG CCT TTC TTT CCT TCT TTT ACC CAA AGA GAA AAA CAG GTT CCA GAG TCA ATC GTT TTA TAT AGA AGT GTT TAC TAT TAC TAC AAA GGA TTT GAG GGC CGG GGA ATT AAA TAC GAT CGC AAC TCA CAC AAA GCT ATT ATC AAC CTT GTC TTT GCC GCC AAT AAT AGA GAT CCA GGT CCT TAT CTA GAG GTG AGA GTA AAG TTG GAA AGG GCA AAG TTT GGT AAT TAT AAT TTT TGC CTT TAC ACC TGC CTA GAA GAT CAT CAA GGA GGT AGA GTA AAA GTT GTT CTG GAG AAC ACT CTT GTT GGT GCA GAG CAA GCT CTC TCT TTC TAC CTT GAT ATG CAC AAG 
cedratDY1                       ATG CTT CAA GTC TAC TCG ACC ATT CTC TCC TTC CAC GAG GAA CCT AAG GAT GCG TAT CGG GTC TGT TCT CTC TTC ATG AAC ATC CTC TCC AGT AAA AGT TTT TGG AAA GAG AGA CAT GAG AGA GAA GGT TTA CCT TGT CTG GAA CAC AAC CTG TCT CAT ATG AGA GCC TAC TAT CTA ACC AGA AAG TTT GTA ACC AAT AAG ACA GTT CTC TCT TGT CAT CTG TCT AAA TTG CCT TTC TTT CCT TCT TTT ACC CAA AGA GAA AAA CAG GTT CCA GAG TCA ATC GTT TTA TAT AGA AGT GTT TAC TAT TAC TAC AAA GGA TTT GAG GGC CGG GGA ATT AAA TAC GAT CGC AAC TCA CAC AAA GCT ATT ATC AAC CTT GTC TTT GCC GCC AAT AAT AGA GAT CCA GGT CCT TAT CTA GAG GTG AGA GTA AAG TTG GAA AGG GCA AAG TTT GGT AAT TAT AAT TTT TGC CTT TAC ACC TGC CTA GAA GAT CAT CAA GGA GGT AGA GTA AAA GTT GTT CTG GAG AAC ACT CTT GTT GGT GCA GAG CAA GCT CTC TCT TTC TAC CTT GAT ATG CAC AAG 
ck                              ATG CTT CAA GTC TAC TCG ACC ATT CTC TCC TTC CAC GAG GAA CCC AAG GAT GCG TAT CGG GTC TGT TCT CTC TTC ATG AAC ATC CTC TCC AGT AAA AGT TTT TGG AAA GAT AGA CAT GAT AGA GAA GGT TTA CCT TGT CTG GAA CAC AAC CTG TCT CAT ATG AGA GCC TAC TAT CTA ACC AGA AAG TTT GTA ACC AAG AAG ACA GTT CTC TCT TGT CAT CTG TCT AAA TTG CCT TTC TCT CCT TCT TTT ATC CAA AGA GAA AAA CAG GTT CCA GAG TCC ATC GTT TTA TAT AGA AGT GTT TAC TAT TAC TAC AAA GGA TTT GAG GGC CGG GGA ATT AAA TAC GAT CGC AAC TCA CAC AAA GCT ATT ATC AAC CTT GTC TTT GCC GCC AAT AAT AGA GAT CCA GGT CCT TAT CTA GAG GTG AGA GTA AAG TTG GAA AGG GCA AAG TTT GGT AAT TAT AAT TTT TGC CTT TAC ACC TGC CTA GAA GAT CAT CAA GGA GGT AGA GTA AAA GTT GTT CTG GAG AAC ACT CTT GTT GGT GCA GAG CAA GCT CTC TCT TTC TAC CTT GAT ATG CAC AAG 



Printing out site pattern counts


         4        333  P

brc                             AAA AAA AAA AAC AAC AAG AAG AAG AAG AAG AAG AAT AAT AAT AAT ACA ACC ACC ACT ACT AGA AGA AGA AGC AGG AGT AGT ATC ATC ATG ATG ATG ATT ATT CAA CAA CAC CAG CAT CCA CCC CCT CGA CGC CGG CGT CTA CTA CTA CTC CTC CTC CTG CTG CTT CTT CTT GAA GAA GAC GAG GAG GAG GAG GAT GAT GAT GCA GCA GCC GCT GCT GGA GGC GGG GGT GGT GGT GTA GTA GTC GTG GTG GTT TAC TAC TAC TAC TAT TAT TAT TAT TCA TCC TCC TCG TCG TCT TCT TGC TGC TGG TGT TGT TTA TTA TTC TTC TTG TTT TTT 
cedratDY0                       ... ..G .G. ... .GT ..A ... ... CG. G.. G.. ..G ... .T. T.. G.. ... .GA ..C ... .A. ... ..G CA. .A. .AC ... ... G.. ... GCA GC. ... G.. ... G.. ... ..A ... ... ..T ... ..G ... .A. G.. ... ..G ..T ... ..T TA. A.. ... ..C ... T.C ... ..G ..T C.T ... ... ... ..G ... .G. A.. ..C ... ..C ... ... .AT AAA A.. ..C ... ... ..C ... ..A ... ... C.. ... ..T .G. A.. ... .G. .T. ... A.. ..A GA. ... ..C ... ... ..T ... CAC ... ... ... ... ..T ... ... ... 
cedratDY1                       ... ..G .G. ... .GT ..A ... ..T CG. G.. G.. ..G ... .T. T.. G.. ... .GA ..C ... .A. ... ..G CA. .A. .AC ... ... G.. ... GCA GC. ... G.. ... G.. ... ..A ... ... ..T ... ..G ... .A. G.. ... ..G ..T ... ..T TA. A.. ... ..C ... T.C ... ..G ..T C.T A.. ... ... ..G ... .G. A.. ..C ... ..C ... ... .AT AAA A.. ..C ... ... ..C ... ..A ... ... C.. ... ..T .G. A.. ... .G. .T. ... A.. ..A GA. ... ..C ... ... ..T ... CAC ... C.. ... ... ..T ... ... ... 
ck                              ... ..G .G. ... .GT ..A ... ... CG. G.. G.T ..G ... .T. T.. G.. ... .GA ..C ... .A. ... ..G CA. .A. .AC ... ... G.. ... GCA GC. ... G.. ... G.. ... ..A ... ... ... ... ..G ... .A. G.. ... ..G ..T ... ..T TA. A.. ... ..C ... T.C ... ..G ..T C.T A.. ... ..T ..G ... .G. A.. ..C ... ..C ... ... .AT AAA A.. ..C ... ... ..C ... ..A ... ... C.. ... ..T .G. A.. ... .G. .T. ... AT. ... GA. ... ..C ... ... ..T ... CAC ... C.. ... ... ..T ... .C. ... 

    5    1    1    3    1    1    2    1    1    1    1    1    3    1    2
    1    2    1    2    1    1    7    1    1    1    2    1    3    1    3
    1    1    2    3    2    1    1    2    3    2    1    4    1    1    1
    1    2    1    1    4    3    1    1    3    1    1    1    5    1    1
    1    1    2    1    1    3    1    1    1    1    1    2    3    1    1
    1    1    3    2    1    1    1    1    4    1    7    1    1    1    3
    1    1    1    1    1    1    1    2    6    1    1    1    1    1    1
    2    3    2    2    1    4

CODONML (in paml version 4.9j, October 2019)  N2.HOG0000435.paml
Model: One dN/dS ratio, 
Codon frequency model: F3x4
ns =   4  ls = 191

Codon usage in sequences
------------------------------------------------------------------------------------------------------
Phe TTT   5   8   8   7 | Ser TCT   8   6   6   7 | Tyr TAT   6   6   6   6 | Cys TGT   2   3   3   3
    TTC   5   4   4   4 |     TCC   2   2   2   3 |     TAC  10   8   8   8 |     TGC   2   2   2   2
Leu TTA   3   3   2   2 |     TCA   1   2   2   1 | *** TAA   0   0   0   0 | *** TGA   0   0   0   0
    TTG   2   2   2   2 |     TCG   2   1   1   1 |     TAG   0   0   0   0 | Trp TGG   1   1   1   1
------------------------------------------------------------------------------------------------------
Leu CTT   3   5   5   5 | Pro CCT   4   5   5   4 | His CAT   3   4   4   4 | Arg CGT   1   0   0   0
    CTC   8   5   5   5 |     CCC   1   0   0   1 |     CAC   1   4   4   4 |     CGC   1   1   1   1
    CTA   4   2   3   3 |     CCA   2   2   2   2 | Gln CAA   3   4   4   4 |     CGA   1   0   0   0
    CTG   4   4   4   4 |     CCG   0   0   0   0 |     CAG   2   1   1   1 |     CGG   1   2   2   2
------------------------------------------------------------------------------------------------------
Ile ATT   5   3   3   3 | Thr ACT   3   1   1   1 | Asn AAT   7   4   5   4 | Ser AGT   3   3   3   3
    ATC   4   3   3   4 |     ACC   3   5   5   4 |     AAC   4   5   5   5 |     AGC   1   0   0   0
    ATA   0   0   0   0 |     ACA   1   1   1   1 | Lys AAA   7   8   8   8 | Arg AGA   9   9   9   9
Met ATG   5   4   4   4 |     ACG   0   0   0   0 |     AAG   7   6   6   7 |     AGG   1   1   1   1
------------------------------------------------------------------------------------------------------
Val GTT   4   7   7   7 | Ala GCT   3   2   2   2 | Asp GAT   5   5   5   7 | Gly GGT   5   5   5   5
    GTC   1   3   3   3 |     GCC   1   3   3   3 |     GAC   1   0   0   0 |     GGC   1   1   1   1
    GTA   3   3   3   3 |     GCA   2   2   2   2 | Glu GAA   6   6   6   6 |     GGA   3   3   3   3
    GTG   2   1   1   1 |     GCG   0   1   1   1 |     GAG   5   9   8   6 |     GGG   1   0   0   0
------------------------------------------------------------------------------------------------------

Codon position x base (3x4) table for each sequence.

#1: brc            
position  1:    T:0.25654    C:0.20419    A:0.31414    G:0.22513
position  2:    T:0.30366    C:0.17277    A:0.35079    G:0.17277
position  3:    T:0.35079    C:0.24084    A:0.23560    G:0.17277
Average         T:0.30366    C:0.20593    A:0.30017    G:0.19023

#2: cedratDY0      
position  1:    T:0.25131    C:0.20419    A:0.27749    G:0.26702
position  2:    T:0.29843    C:0.17277    A:0.36649    G:0.16230
position  3:    T:0.35079    C:0.24084    A:0.23560    G:0.17277
Average         T:0.30017    C:0.20593    A:0.29319    G:0.20070

#3: cedratDY1      
position  1:    T:0.24607    C:0.20942    A:0.28272    G:0.26178
position  2:    T:0.29843    C:0.17277    A:0.36649    G:0.16230
position  3:    T:0.35602    C:0.24084    A:0.23560    G:0.16754
Average         T:0.30017    C:0.20768    A:0.29494    G:0.19721

#4: ck             
position  1:    T:0.24607    C:0.20942    A:0.28272    G:0.26178
position  2:    T:0.29843    C:0.17277    A:0.36649    G:0.16230
position  3:    T:0.35602    C:0.25131    A:0.23037    G:0.16230
Average         T:0.30017    C:0.21117    A:0.29319    G:0.19546

Sums of codon usage counts
------------------------------------------------------------------------------
Phe F TTT      28 | Ser S TCT      27 | Tyr Y TAT      24 | Cys C TGT      11
      TTC      17 |       TCC       9 |       TAC      34 |       TGC       8
Leu L TTA      10 |       TCA       6 | *** * TAA       0 | *** * TGA       0
      TTG       8 |       TCG       5 |       TAG       0 | Trp W TGG       4
------------------------------------------------------------------------------
Leu L CTT      18 | Pro P CCT      18 | His H CAT      15 | Arg R CGT       1
      CTC      23 |       CCC       2 |       CAC      13 |       CGC       4
      CTA      12 |       CCA       8 | Gln Q CAA      15 |       CGA       1
      CTG      16 |       CCG       0 |       CAG       5 |       CGG       7
------------------------------------------------------------------------------
Ile I ATT      14 | Thr T ACT       6 | Asn N AAT      20 | Ser S AGT      12
      ATC      14 |       ACC      17 |       AAC      19 |       AGC       1
      ATA       0 |       ACA       4 | Lys K AAA      31 | Arg R AGA      36
Met M ATG      17 |       ACG       0 |       AAG      26 |       AGG       4
------------------------------------------------------------------------------
Val V GTT      25 | Ala A GCT       9 | Asp D GAT      22 | Gly G GGT      20
      GTC      10 |       GCC      10 |       GAC       1 |       GGC       4
      GTA      12 |       GCA       8 | Glu E GAA      24 |       GGA      12
      GTG       5 |       GCG       3 |       GAG      28 |       GGG       1
------------------------------------------------------------------------------


Codon position x base (3x4) table, overall

position  1:    T:0.25000    C:0.20681    A:0.28927    G:0.25393
position  2:    T:0.29974    C:0.17277    A:0.36257    G:0.16492
position  3:    T:0.35340    C:0.24346    A:0.23429    G:0.16885
Average         T:0.30105    C:0.20768    A:0.29538    G:0.19590

Codon frequencies under model, for use in evolver (TTT TTC TTA TTG ... GGG):
  0.02776488  0.01912692  0.01840709  0.01326544
  0.01600421  0.01102512  0.01061020  0.00764646
  0.03358459  0.02313605  0.00000000  0.00000000
  0.01527675  0.01052398  0.00000000  0.00729889
  0.02296781  0.01582227  0.01522681  0.01097351
  0.01323908  0.00912026  0.00877702  0.00632534
  0.02778202  0.01913872  0.01841845  0.01327363
  0.01263731  0.00870570  0.00837807  0.00603783
  0.03212586  0.02213115  0.02129825  0.01534902
  0.01851796  0.01275682  0.01227672  0.00884747
  0.03885966  0.02676999  0.02576252  0.01856628
  0.01767624  0.01217696  0.01171869  0.00844531
  0.02820098  0.01942734  0.01869620  0.01347380
  0.01625559  0.01119829  0.01077685  0.00776656
  0.03411210  0.02349945  0.02261506  0.01629800
  0.01551670  0.01068928  0.01028699  0.00741353


TREE #  1:  ((4, (2, 3)), 1);   MP score: 81
This is a rooted tree.  Please check!
lnL(ntime:  6  np:  8):  -1145.851997      +0.000000
   5..6     6..4     6..7     7..2     7..3     5..1  
 0.243497 0.022144 0.010203 0.010412 0.005552 0.326541 5.026836 0.543557

Note: Branch length is defined as number of nucleotide substitutions per codon (not per neucleotide site).

tree length =  0.618349

((4: 0.022144, (2: 0.010412, 3: 0.005552): 0.010203): 0.243497, 1: 0.326541);

((ck: 0.022144, (cedratDY0: 0.010412, cedratDY1: 0.005552): 0.010203): 0.243497, brc: 0.326541);

Detailed output identifying parameters

kappa (ts/tv) =  5.02684

omega (dN/dS) =  0.54356

dN & dS for each branch

 branch          t       N       S   dN/dS      dN      dS  N*dN  S*dS

   5..6      0.243   407.6   165.4  0.5436  0.0653  0.1202  26.6  19.9
   6..4      0.022   407.6   165.4  0.5436  0.0059  0.0109   2.4   1.8
   6..7      0.010   407.6   165.4  0.5436  0.0027  0.0050   1.1   0.8
   7..2      0.010   407.6   165.4  0.5436  0.0028  0.0051   1.1   0.8
   7..3      0.006   407.6   165.4  0.5436  0.0015  0.0027   0.6   0.5
   5..1      0.327   407.6   165.4  0.5436  0.0876  0.1612  35.7  26.7

tree length for dN:       0.1659
tree length for dS:       0.3052


Time used:  0:03
`

**Comment by peterjc** [comment]
@lalalagartija please clarify if you have the latest Biopython release (version 1.79), or the latest source code from github?

Also, which version of PAML?

**Comment by lalalagartija** [comment]
Hi @peterjc, I actually tried both versions and both failed.

**Comment by peterjc** [comment]
@lalalagartija I think you should open a new issue with a reproducible test case (and upload the problem file as an attachment, not text within the comment). Thanks.
